{
    "IDEB - Anos Iniciais": "Traceback (most recent call last):\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\g17.1--g17.2--g17.3--g17.4--t17.1--t17.2.py\", line 145, in <module>\n    data = c.open_file(dbs_path, os.listdir(dbs_path)[0], ext='zip', excel_name='divulgacao', skiprows=9)\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\functions.py\", line 124, in open_file\n    with zipfile.ZipFile(os.path.join(dir_path, file_path), 'r') as zfile:\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\zipfile.py\", line 1269, in __init__\n    self._RealGetContents()\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\zipfile.py\", line 1336, in _RealGetContents\n    raise BadZipFile(\"File is not a zip file\")\nzipfile.BadZipFile: File is not a zip file\n",
    "IDEB Resultados": "Traceback (most recent call last):\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\g17.1--g17.2--g17.3--g17.4--t17.1--t17.2.py\", line 169, in <module>\n    driver = c.Google(visible=False, rep=dbs_path)  # instância do objeto driver do Selenium\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\functions.py\", line 186, in __init__\n    self.browser = webdriver.Chrome(options=self.options)\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 208, in __init__\n    self.start_session(capabilities)\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 292, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.SessionNotCreatedException: Message: session not created\nfrom disconnected: unable to connect to renderer\nStacktrace:\n\tGetHandleVerifier [0x0x7ff7fb8afca5+79861]\n\tGetHandleVerifier [0x0x7ff7fb8afd00+79952]\n\t(No symbol) [0x0x7ff7fb62cada]\n\t(No symbol) [0x0x7ff7fb6716cb]\n\t(No symbol) [0x0x7ff7fb66ae5c]\n\t(No symbol) [0x0x7ff7fb666340]\n\t(No symbol) [0x0x7ff7fb6ba84f]\n\t(No symbol) [0x0x7ff7fb6b9fd0]\n\t(No symbol) [0x0x7ff7fb6ac8b3]\n\t(No symbol) [0x0x7ff7fb675272]\n\t(No symbol) [0x0x7ff7fb676043]\n\tGetHandleVerifier [0x0x7ff7fbb6b9dd+2946349]\n\tGetHandleVerifier [0x0x7ff7fbb65c5a+2922410]\n\tGetHandleVerifier [0x0x7ff7fbb859e7+3052855]\n\tGetHandleVerifier [0x0x7ff7fb8caa8e+189918]\n\tGetHandleVerifier [0x0x7ff7fb8d2a2f+222591]\n\tGetHandleVerifier [0x0x7ff7fb8b8ac4+116244]\n\tGetHandleVerifier [0x0x7ff7fb8b8c79+116681]\n\tGetHandleVerifier [0x0x7ff7fb89f058+11176]\n\tBaseThreadInitThunk [0x0x7ff96281e8d7+23]\n\tRtlUserThreadStart [0x0x7ff96337c34c+44]\n\n",
    "Gráfico 17.3": "Traceback (most recent call last):\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\g17.1--g17.2--g17.3--g17.4--t17.1--t17.2.py\", line 280, in <module>\n    data = c.open_file(dbs_path, 'ideb_resultados.xlsx', 'xls', sheet_name='Sheet1').query(\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\functions.py\", line 106, in open_file\n    dataframe = pd.read_excel(os.path.join(dir_path, file_path),\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 495, in read_excel\n    io = ExcelFile(\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 1550, in __init__\n    ext = inspect_excel_format(\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 1402, in inspect_excel_format\n    with get_handle(\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\common.py\", line 882, in get_handle\n    handle = open(handle, ioargs.mode)\nFileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\RUNNER~1\\\\AppData\\\\Local\\\\Temp\\\\tmp6obqrgsd\\\\ideb_resultados.xlsx'\n",
    "Gráfico 17.4": "Traceback (most recent call last):\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\g17.1--g17.2--g17.3--g17.4--t17.1--t17.2.py\", line 301, in <module>\n    data = c.open_file(dbs_path, 'ideb_resultados.xlsx', 'xls', sheet_name='Sheet1').query(\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\functions.py\", line 106, in open_file\n    dataframe = pd.read_excel(os.path.join(dir_path, file_path),\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 495, in read_excel\n    io = ExcelFile(\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 1550, in __init__\n    ext = inspect_excel_format(\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 1402, in inspect_excel_format\n    with get_handle(\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\common.py\", line 882, in get_handle\n    handle = open(handle, ioargs.mode)\nFileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\RUNNER~1\\\\AppData\\\\Local\\\\Temp\\\\tmp6obqrgsd\\\\ideb_resultados.xlsx'\n",
    "Tabela 17.2": "Traceback (most recent call last):\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\g17.1--g17.2--g17.3--g17.4--t17.1--t17.2.py\", line 322, in <module>\n    data = c.open_file(dbs_path, 'ideb_resultados.xlsx', 'xls', sheet_name='Sheet1').query('`Região` == \"Sergipe\"')\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\functions.py\", line 106, in open_file\n    dataframe = pd.read_excel(os.path.join(dir_path, file_path),\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 495, in read_excel\n    io = ExcelFile(\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 1550, in __init__\n    ext = inspect_excel_format(\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 1402, in inspect_excel_format\n    with get_handle(\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\common.py\", line 882, in get_handle\n    handle = open(handle, ioargs.mode)\nFileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\RUNNER~1\\\\AppData\\\\Local\\\\Temp\\\\tmp6obqrgsd\\\\ideb_resultados.xlsx'\n"
}