{
    "http://siops-asp.datasus.gov.br/cgi/tabcgi.exe?SIOPS/SerHist/ESTADO/indicuf.def": "Traceback (most recent call last):\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\g18.1--g18.2.py\", line 38, in <module>\n    driver = c.Google(visible=False, rep=dbs_path)  # instância do objeto driver do Selenium\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\functions.py\", line 183, in __init__\n    self.browser = webdriver.Chrome(options=self.options)\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 208, in __init__\n    self.start_session(capabilities)\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 292, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.SessionNotCreatedException: Message: session not created\nfrom disconnected: unable to connect to renderer\nStacktrace:\n\tGetHandleVerifier [0x0x7ff74d5cfca5+79861]\n\tGetHandleVerifier [0x0x7ff74d5cfd00+79952]\n\t(No symbol) [0x0x7ff74d34cada]\n\t(No symbol) [0x0x7ff74d3916cb]\n\t(No symbol) [0x0x7ff74d38ae5c]\n\t(No symbol) [0x0x7ff74d386340]\n\t(No symbol) [0x0x7ff74d3da84f]\n\t(No symbol) [0x0x7ff74d3d9fd0]\n\t(No symbol) [0x0x7ff74d3cc8b3]\n\t(No symbol) [0x0x7ff74d395272]\n\t(No symbol) [0x0x7ff74d396043]\n\tGetHandleVerifier [0x0x7ff74d88b9dd+2946349]\n\tGetHandleVerifier [0x0x7ff74d885c5a+2922410]\n\tGetHandleVerifier [0x0x7ff74d8a59e7+3052855]\n\tGetHandleVerifier [0x0x7ff74d5eaa8e+189918]\n\tGetHandleVerifier [0x0x7ff74d5f2a2f+222591]\n\tGetHandleVerifier [0x0x7ff74d5d8ac4+116244]\n\tGetHandleVerifier [0x0x7ff74d5d8c79+116681]\n\tGetHandleVerifier [0x0x7ff74d5bf058+11176]\n\tBaseThreadInitThunk [0x0x7ff94942e8d7+23]\n\tRtlUserThreadStart [0x0x7ff949e1c34c+44]\n\n",
    "Gráfico 18.1": "Traceback (most recent call last):\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\g18.1--g18.2.py\", line 75, in <module>\n    df = c.open_file(dbs_path, os.listdir(dbs_path)[0], 'csv', sep=';', encoding='cp1252', skiprows=3)\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\functions.py\", line 95, in open_file\n    dataframe = pd.read_csv(os.path.join(dir_path, file_path),\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 1026, in read_csv\n    return _read(filepath_or_buffer, kwds)\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 626, in _read\n    return parser.read(nrows)\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 1923, in read\n    ) = self._engine.read(  # type: ignore[attr-defined]\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\parsers\\c_parser_wrapper.py\", line 234, in read\n    chunks = self._reader.read_low_memory(nrows)\n  File \"parsers.pyx\", line 838, in pandas._libs.parsers.TextReader.read_low_memory\n  File \"parsers.pyx\", line 905, in pandas._libs.parsers.TextReader._read_rows\n  File \"parsers.pyx\", line 874, in pandas._libs.parsers.TextReader._tokenize_rows\n  File \"parsers.pyx\", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status\n  File \"parsers.pyx\", line 2061, in pandas._libs.parsers.raise_parser_error\npandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 6, saw 2\n\n",
    "Gráfico 18.2": "Traceback (most recent call last):\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\g18.1--g18.2.py\", line 142, in <module>\n    df = c.open_file(dbs_path, os.listdir(dbs_path)[0], 'csv', sep=';', encoding='cp1252', skiprows=3)\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\functions.py\", line 95, in open_file\n    dataframe = pd.read_csv(os.path.join(dir_path, file_path),\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 1026, in read_csv\n    return _read(filepath_or_buffer, kwds)\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 626, in _read\n    return parser.read(nrows)\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 1923, in read\n    ) = self._engine.read(  # type: ignore[attr-defined]\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\parsers\\c_parser_wrapper.py\", line 234, in read\n    chunks = self._reader.read_low_memory(nrows)\n  File \"parsers.pyx\", line 838, in pandas._libs.parsers.TextReader.read_low_memory\n  File \"parsers.pyx\", line 905, in pandas._libs.parsers.TextReader._read_rows\n  File \"parsers.pyx\", line 874, in pandas._libs.parsers.TextReader._tokenize_rows\n  File \"parsers.pyx\", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status\n  File \"parsers.pyx\", line 2061, in pandas._libs.parsers.raise_parser_error\npandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 6, saw 2\n\n"
}