{
    "http://tabnet.datasus.gov.br/cgi/deftohtm.exe?cnes/cnv/equipobr.def": "Traceback (most recent call last):\n  File \"/home/runner/work/T25/T25/Scripts/Daniel/t18.2.py\", line 31, in <module>\n    driver.get(url)  # acessa a página\n  File \"/home/runner/work/T25/T25/Scripts/Daniel/functions.py\", line 159, in get\n    self.browser.get(url)\n  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 356, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.901\n  (Session info: chrome=131.0.6778.0)\nStacktrace:\n#0 0x563deb4d54ca <unknown>\n#1 0x563deafe8620 <unknown>\n#2 0x563deafd0907 <unknown>\n#3 0x563deafd05de <unknown>\n#4 0x563deafce616 <unknown>\n#5 0x563deafcedff <unknown>\n#6 0x563deafde687 <unknown>\n#7 0x563deaff54a4 <unknown>\n#8 0x563deaffb32b <unknown>\n#9 0x563deafcf507 <unknown>\n#10 0x563deaff5304 <unknown>\n#11 0x563deb07a15f <unknown>\n#12 0x563deb05b113 <unknown>\n#13 0x563deb029be0 <unknown>\n#14 0x563deb02abbe <unknown>\n#15 0x563deb4a1e4b <unknown>\n#16 0x563deb4a5de2 <unknown>\n#17 0x563deb48ed2c <unknown>\n#18 0x563deb4a6957 <unknown>\n#19 0x563deb4744bf <unknown>\n#20 0x563deb4c4348 <unknown>\n#21 0x563deb4c4510 <unknown>\n#22 0x563deb4d4346 <unknown>\n#23 0x7f18ed094ac3 <unknown>\n\n",
    "http://tabnet.datasus.gov.br/cgi/deftohtm.exe?ibge/cnv/projpopuf.def (POPULAÇÃO)": "Traceback (most recent call last):\n  File \"/home/runner/work/T25/T25/Scripts/Daniel/t18.2.py\", line 85, in <module>\n    driver.get(url)  # acessa a página\n  File \"/home/runner/work/T25/T25/Scripts/Daniel/functions.py\", line 159, in get\n    self.browser.get(url)\n  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 356, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299.229\n  (Session info: chrome=131.0.6778.0)\nStacktrace:\n#0 0x563deb4d54ca <unknown>\n#1 0x563deafe8620 <unknown>\n#2 0x563deafd0907 <unknown>\n#3 0x563deafd05de <unknown>\n#4 0x563deafce616 <unknown>\n#5 0x563deafcedff <unknown>\n#6 0x563deafde687 <unknown>\n#7 0x563deaff54a4 <unknown>\n#8 0x563deaffb32b <unknown>\n#9 0x563deafcf507 <unknown>\n#10 0x563deaff5304 <unknown>\n#11 0x563deb07a15f <unknown>\n#12 0x563deb05b113 <unknown>\n#13 0x563deb029be0 <unknown>\n#14 0x563deb02abbe <unknown>\n#15 0x563deb4a1e4b <unknown>\n#16 0x563deb4a5de2 <unknown>\n#17 0x563deb48ed2c <unknown>\n#18 0x563deb4a6957 <unknown>\n#19 0x563deb4744bf <unknown>\n#20 0x563deb4c4348 <unknown>\n#21 0x563deb4c4510 <unknown>\n#22 0x563deb4d4346 <unknown>\n#23 0x7f18ed094ac3 <unknown>\n\n",
    "Tabela 18.2": "Traceback (most recent call last):\n  File \"/home/runner/work/T25/T25/Scripts/Daniel/t18.2.py\", line 152, in <module>\n    data = c.open_file(dbs_path, pop_file, 'csv', sep=';', encoding='cp1252', skiprows=3)\nNameError: name 'pop_file' is not defined\n"
}