{
    "http://tabnet.datasus.gov.br/cgi/deftohtm.exe?sim/cnv/evitb10uf.def (PRIMEIRA BASE)": "Traceback (most recent call last):\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\g18.8.py\", line 33, in <module>\n    driver.click([\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\functions.py\", line 211, in click\n    button = self.browser.find_element(By.XPATH, path)\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div/center/div/form/div[2]/div/div[1]/select/option[2]\"}\n  (Session info: chrome=140.0.7339.185); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x0x7ff75fa3fca5+79861]\n\tGetHandleVerifier [0x0x7ff75fa3fd00+79952]\n\t(No symbol) [0x0x7ff75f7bcada]\n\t(No symbol) [0x0x7ff75f814457]\n\t(No symbol) [0x0x7ff75f81471c]\n\t(No symbol) [0x0x7ff75f868217]\n\t(No symbol) [0x0x7ff75f83cb1f]\n\t(No symbol) [0x0x7ff75f864f8b]\n\t(No symbol) [0x0x7ff75f83c8b3]\n\t(No symbol) [0x0x7ff75f805272]\n\t(No symbol) [0x0x7ff75f806043]\n\tGetHandleVerifier [0x0x7ff75fcfb9dd+2946349]\n\tGetHandleVerifier [0x0x7ff75fcf5c5a+2922410]\n\tGetHandleVerifier [0x0x7ff75fd159e7+3052855]\n\tGetHandleVerifier [0x0x7ff75fa5aa8e+189918]\n\tGetHandleVerifier [0x0x7ff75fa62a2f+222591]\n\tGetHandleVerifier [0x0x7ff75fa48ac4+116244]\n\tGetHandleVerifier [0x0x7ff75fa48c79+116681]\n\tGetHandleVerifier [0x0x7ff75fa2f058+11176]\n\tBaseThreadInitThunk [0x0x7ffbe954e8d7+23]\n\tRtlUserThreadStart [0x0x7ffbea65c34c+44]\n\n",
    "http://tabnet.datasus.gov.br/cgi/deftohtm.exe?ibge/cnv/projpopuf.def (SEGUNDA BASE)": "Traceback (most recent call last):\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\g18.8.py\", line 83, in <module>\n    driver.click([\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\functions.py\", line 211, in click\n    button = self.browser.find_element(By.XPATH, path)\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div/center/div/form/div[2]/div/div[1]/select/option[2]\"}\n  (Session info: chrome=140.0.7339.185); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x0x7ff75fa3fca5+79861]\n\tGetHandleVerifier [0x0x7ff75fa3fd00+79952]\n\t(No symbol) [0x0x7ff75f7bcada]\n\t(No symbol) [0x0x7ff75f814457]\n\t(No symbol) [0x0x7ff75f81471c]\n\t(No symbol) [0x0x7ff75f868217]\n\t(No symbol) [0x0x7ff75f83cb1f]\n\t(No symbol) [0x0x7ff75f864f8b]\n\t(No symbol) [0x0x7ff75f83c8b3]\n\t(No symbol) [0x0x7ff75f805272]\n\t(No symbol) [0x0x7ff75f806043]\n\tGetHandleVerifier [0x0x7ff75fcfb9dd+2946349]\n\tGetHandleVerifier [0x0x7ff75fcf5c5a+2922410]\n\tGetHandleVerifier [0x0x7ff75fd159e7+3052855]\n\tGetHandleVerifier [0x0x7ff75fa5aa8e+189918]\n\tGetHandleVerifier [0x0x7ff75fa62a2f+222591]\n\tGetHandleVerifier [0x0x7ff75fa48ac4+116244]\n\tGetHandleVerifier [0x0x7ff75fa48c79+116681]\n\tGetHandleVerifier [0x0x7ff75fa2f058+11176]\n\tBaseThreadInitThunk [0x0x7ffbe954e8d7+23]\n\tRtlUserThreadStart [0x0x7ffbea65c34c+44]\n\n",
    "Gr√°fico 18.8": "Traceback (most recent call last):\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\g18.8.py\", line 140, in <module>\n    data = c.open_file(dbs_path, f, 'csv')\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\functions.py\", line 95, in open_file\n    dataframe = pd.read_csv(os.path.join(dir_path, file_path),\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 1026, in read_csv\n    return _read(filepath_or_buffer, kwds)\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 620, in _read\n    parser = TextFileReader(filepath_or_buffer, **kwds)\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 1620, in __init__\n    self._engine = self._make_engine(f, self.engine)\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 1880, in _make_engine\n    self.handles = get_handle(\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\common.py\", line 882, in get_handle\n    handle = open(handle, ioargs.mode)\nFileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\RUNNER~1\\\\AppData\\\\Local\\\\Temp\\\\tmp9ha6jyjx\\\\base1.csv'\n"
}